controller_manager:
  ros__parameters:
    update_rate: 100

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    gripper_controller:
      type: velocity_controllers/JointGroupVelocityController

# Gripper
gripper_controller:
  ros__parameters:
    joints:
      - base_arm_joint
      - ton_arm_joint
      - last_arm_joint
      - hand_joint
      - finger_joint
      - finger1_joint
    command_interfaces:
      - velocity
    state_interfaces:
      - position
      - velocity